#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/utils.js:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/utils.js
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xdc.tci:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xdc.tci
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/template.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/template.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/om2.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/om2.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xmlgen.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xmlgen.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xmlgen2.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/xmlgen2.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/Warnings.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/Warnings.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/IPackage.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/IPackage.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/package.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/package.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/global/Clock.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/global/Clock.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/global/Trace.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/global/Trace.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/bld.js:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/bld.js
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/BuildEnvironment.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/PackageContents.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/PackageContents.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/_gen.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/_gen.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Library.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Library.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Executable.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Executable.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Repository.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Repository.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Configuration.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Configuration.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Script.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Script.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Manifest.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Manifest.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Utils.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/Utils.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget2.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget2.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget3.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget3.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/ITargetFilter.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/package.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/bld/package.xs
package.mak: config.bld
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/_utils.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/_utils.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/IM.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/IM.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/M3.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/M3.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A8F.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A8F.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A9F.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A9F.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A15F.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A15F.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A53F.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A53F.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A72F.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/A72F.xs
/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/package.xs:
package.mak: /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/package.xs
package.mak: package.bld
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/io/File.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/io/File.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/io/package.xs:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/services/io/package.xs
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/sascha/ti/ccs1000/xdctools_3_61_00_16_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.M4F.rootDir ?= /home/sascha/ti/ccs1000/ccs/tools/compiler/gcc-arm-none-eabi-9-2019-q4-major
gnu.targets.arm.packageBase ?= /home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.om4fg
.PHONY: all,m4fg .dlls,m4fg .executables,m4fg test,m4fg
all,m4fg: .executables,m4fg
.executables,m4fg: .libraries,m4fg
.executables,m4fg: .dlls,m4fg
.dlls,m4fg: .libraries,m4fg
.libraries,m4fg: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4fg
	@$(ECHO) xdc .executables,m4fg
	@$(ECHO) xdc .libraries,m4fg
	@$(ECHO) xdc .dlls,m4fg


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,m4fg .dlls: blinky.pm4fg

-include package/cfg/blinky_pm4fg.mak
-include package/cfg/blinky_pm4fg.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/blinky_pm4fg.dep
endif
blinky.pm4fg: package/cfg/blinky_pm4fg.xdl
	@


ifeq (,$(wildcard .libraries,m4fg))
blinky.pm4fg package/cfg/blinky_pm4fg.c: .libraries,m4fg
endif

package/cfg/blinky_pm4fg.c package/cfg/blinky_pm4fg.h package/cfg/blinky_pm4fg.xdl: override _PROG_NAME := blinky.xm4fg
package/cfg/blinky_pm4fg.c: package/cfg/blinky_pm4fg.cfg
package/cfg/blinky_pm4fg.xdc.inc: package/cfg/blinky_pm4fg.xdl
package/cfg/blinky_pm4fg.xdl package/cfg/blinky_pm4fg.c: .interfaces

clean:: clean,m4fg
	-$(RM) package/cfg/blinky_pm4fg.cfg
	-$(RM) package/cfg/blinky_pm4fg.dep
	-$(RM) package/cfg/blinky_pm4fg.c
	-$(RM) package/cfg/blinky_pm4fg.xdc.inc

clean,m4fg::
	-$(RM) blinky.pm4fg
.executables,m4fg .executables: blinky.xm4fg

blinky.xm4fg: |blinky.pm4fg

-include package/cfg/blinky.xm4fg.mak
blinky.xm4fg: package/cfg/blinky_pm4fg.om4fg 
	$(RM) $@
	@$(MSG) lnkm4fg $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -nostartfiles -Wl,-static -Wl,--gc-sections     -o $@ package/cfg/blinky_pm4fg.om4fg -Wl,-T,package/cfg/blinky_pm4fg.xdl   -L/home/sascha/ti/simplelink_cc13x2_26x2_sdk_4_20_00_35/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/lib/thumb/v7e-m/hard -Wl,--start-group -lgcc -lc -lm -Wl,--end-group --specs=nano.specs -Wl,-Map=$(XDCCFGDIR)/$@.map --specs=nosys.specs
	
blinky.xm4fg: export LD_LIBRARY_PATH=

blinky.test test,m4fg test: blinky.xm4fg.test

blinky.xm4fg.test:: blinky.xm4fg
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 blinky.xm4fg.test
else
	@$(MSG) running $<  ...
	$(call EXEC.blinky.xm4fg, ) 
endif

clean,m4fg::
	-$(RM) $(wildcard .tmp,blinky.xm4fg,*)


clean:: clean,m4fg

clean,m4fg::
	-$(RM) blinky.xm4fg
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
blinky_pm4fg.om4fg,copy : package/cfg/blinky_pm4fg.om4fg
blinky_pm4fg.sm4fg,copy : package/cfg/blinky_pm4fg.sm4fg

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
